################################
##  Name selection priority
################################


--- taglist
---

label:          [ name, loc_name, operator ]
house:          [ addr:housenumber, addr:housename ]
entrance:       [ name, ref ]
place:          [ addr:city, place_name, name ]
suburb:         [ addr:suburb, place_name, name ]
street:         [ addr:street, name ]
region:         [ addr:region, is_in:region, addr:state, is_in:state ]
country:        [ addr:country, is_in:country_code, is_in:country ]
destination:    [ destination, label, name ]
note:           [ note ]



################################
##  Tags to skip
################################


--- skip_tags
---

created_by:         1



################################
##  Tags for comment
################################


--- comment
---

access:             1
aerialway:          1
aeroway:            1
admin_level:        1
amenity:            1
barrier:            1
boundary:           1
bridge:             1
building:           1
capital:            1
highway:            1
historic:           1
junction:           1
layer:              1
landuse:            1
leisure:            1
man_made:           1
military:           1
natural:            1
place:              1
power:              1
railway:            1
religion:           1
route:              1
service:            1
shop:               1
sport:              1
surface:            1
tourism:            1
tracktype:          1
traffic_calming:    1
tunnel:             1
waterway:           1
whitewater:         1
  


################################
##  Common types
################################


--- types
---

background:
    type:       0x4B
    endlevel:   4

sea:
    type:       0x3C
    endlevel:   4
  


################################
##  Access restrictions
################################


--- yesno
---

1:              1
yes:            1
true:           1
designated:     1
permissive:     1

0:              0
no:             0
false:          0
private:        0
restricted:     0
destination:    0
  


################################
##  Transport restrictions
################################

# emergency, delivery, car, bus, taxi, foot, bike, truck

--- transport
---

- key:     motorroad
  val:     0,0,0,0,0,1,1,0
  mode:    -1

- key:     access
  val:     1,1,1,1,1,1,1,1

- key:     vehicle
  val:     1,1,1,1,1,0,1,1
- key:     motor_vehicle
  val:     1,1,1,1,1,0,0,1

- key:     motorcar
  val:     1,1,1,1,1,0,0,1

- key:     foot
  val:     0,0,0,0,0,1,0,0
- key:     bicycle
  val:     0,0,0,0,0,0,1,0
- key:     psv
  val:     0,0,0,1,1,0,0,0
- key:     bus
  val:     0,0,0,1,0,0,0,0
- key:     taxi
  val:     0,0,0,0,1,0,0,0
- key:     hgv
  val:     0,0,0,0,0,0,0,1
- key:     goods
  val:     0,1,0,0,0,0,0,0
- key:     emergency
  val:     1,0,0,0,0,0,0,0
  


################################
##  Barriers
################################

# emergency, delivery, car, bus, taxi, foot, bike, truck
# default: 1,1,1,1,1,1,1,1 - restricts all

--- barrier
---

block:          1,1,1,1,1,0,1,1
stile:          1,1,1,1,1,0,1,1
chain:          1,1,1,1,1,0,1,1
bollard:        1,1,1,1,1,0,0,1
bus_trap:       1,1,1,0,1,0,0,1
toll_booth:     0,0,0,0,0,0,0,0
cattle_grid:    0,0,0,0,0,0,0,0



