
################################
##  Access restrictions
################################


--- yesno
---

1:              1
yes:            1
true:           1
designated:     1
permissive:     1

0:              0
no:             0
false:          0
private:        0
restricted:     0
destination:    0
  





################################
##  Transport restrictions
################################

--- transport_types
---
-
  - emergency
  - police
-
  - delivery
  - goods
-
  - car
  - motorcar
-
  - bus
-
  - taxi
-
  - foot
  - pedestrian
-
  - bike
  - bicycle
-
  - truck
  - hgv



--- transport
---

- key:     motorroad
  val:     0,0,0,0,0,1,1,0
  mode:    -1

- key:     access
  val:     1,1,1,1,1,1,1,1

- key:     vehicle
  val:     1,1,1,1,1,0,1,1
- key:     motor_vehicle
  val:     1,1,1,1,1,0,0,1

- key:     motorcar
  val:     1,1,1,1,1,0,0,1

- key:     foot
  val:     0,0,0,0,0,1,0,0
- key:     bicycle
  val:     0,0,0,0,0,0,1,0
- key:     psv
  val:     0,0,0,1,1,0,0,0
- key:     bus
  val:     0,0,0,1,0,0,0,0
- key:     taxi
  val:     0,0,0,0,1,0,0,0
- key:     hgv
  val:     0,0,0,0,0,0,0,1
- key:     goods
  val:     0,1,0,0,0,0,0,0
- key:     emergency
  val:     1,0,0,0,0,0,0,0
  


################################
##  Barriers
################################

# emergency, delivery, car, bus, taxi, foot, bike, truck
# default: 1,1,1,1,1,1,1,1 - restricts all

--- barrier
---

block:          1,1,1,1,1,0,1,1
stile:          1,1,1,1,1,0,1,1
chain:          1,1,1,1,1,0,1,1
bollard:        1,1,1,1,1,0,0,1
bus_trap:       1,1,1,0,1,0,0,1
toll_booth:     0,0,0,0,0,0,0,0
cattle_grid:    0,0,0,0,0,0,0,0



